image: ubuntu:focal

prepare-environment:
  script:
    - apt-get -qq update
    - apt-get -qq install -y python3-dev python3-pip
    - apt-get -qq install python-pytest
    - pip install -r requirements.txt

run-test:
  script:
    - PYTHONPATH=. pytest
