image: ubuntu:focal

variables:
  GIT_SUBMODULE_STRATEGY: recursive

run-test:
  before_script:
    - apt-get -qq update
    - apt-get -qq install -y python3-dev python3-pip
    - apt-get -qq install python-pytest
    - pip install -r requirements.txt
  script:
    - PYTHONPATH=. pytest
