# This workflow will install Python dependencies and run tests
name: Python package

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        PYTHONPATH=. pytest
